export const FETCH_SOURCES = 'FETCH_SOURCES';
export const FETCH_SOURCES_LOADING = 'FETCH_SOURCES_LOADING';
export const FETCH_SOURCES_SUCCESS = 'FETCH_SOURCES_SUCCESS';
export const FETCH_SOURCES_FAILURE = 'FETCH_SOURCES_FAILURE';

export const FETCH_NEWS = 'FETCH_NEWS';
export const FETCH_NEWS_LOADING = 'FETCH_NEWS_LOADING';
export const FETCH_NEWS_SUCCESS = 'FETCH_NEWS_SUCCESS';
export const FETCH_NEWS_FAILURE = 'FETCH_NEWS_FAILURE';

